/* SQL statements to create the tables necessary for the application */

CREATE TABLE Bidder (
  UserID VARCHAR(80) NOT NULL,
  Rating INTEGER NOT NULL,
  Location VARCHAR(80) DEFAULT NULL,
  Country VARCHAR(80) DEAFULT NULL,

  PRIMARY KEY (UserID)
);

CREATE TABLE Seller (
  UserID VARCHAR(80) NOT NULL,
  Rating INTEGER NOT NULL,

  PRIMARY KEY (UserID)
);

CREATE TABLE Bid (
  ItemID INTEGER NOT NULL,
  UserID VARCHAR(80) NOT NULL,
  Time TIMESTAMP NOT NULL,
  Amount DECIMAL(8, 2) NOT NULL,

  PRIMARY KEY (ItemID, UserID, Time),
  FOREIGN KEY (ItemID) REFERENCES Item(ItemID),
  FOREIGN KEY (UserID) REFERENCES Bidder(UserID)
);

CREATE TABLE Item (
  ItemID INTEGER NOT NULL,
  Name VARCHAR(80) NOT NULL,
  Buy_Price DECIMAL(8, 2) DEFAULT NULL,
  First_Bid DECIMAL(8, 2) NOT NULL,
  Number_of_Bids INTEGER NOT NULL,
  Location VARCHAR(80) NOT NULL,
  Latitude DECIMAL(8, 6) DEFAULT NULL,
  Longitude DECIMAL(8, 6) DEFAULT NULL,
  Currently DECIMAL(8, 2) NOT NULL,
  Country VARCHAR(80) NOT NULL,
  Started TIMESTAMP NOT NULL,
  Ends TIMESTAMP NOT NULL,
  Seller INTEGER NOT NULL,
  Description VARCHAR(4000) NOT NULL,

  PRIMARY KEY (ItemID),
  FOREIGN KEY Seller REFERENCES Seller(UserID)
);

CREATE TABLE ItemCategory (
  ItemID INTEGER NOT NULL,
  Category VARCHAR(80) NOT NULL,

  PRIMARY KEY (ItemID, Category),
  FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);
